#!/usr/bin/python3
##/usr/bin/env python3
# matthew.lewis@utsouthwestern.edu

from tkinter import Tk
from tkinter.messagebox import showinfo
import sys
import struct 
import pickle 

root = Tk()
root.withdraw()
showinfo(title="Bad MF", message="TB is the GOAT")
root.destroy()

#raw_length = sys.stdin.buffer.read(4)
#print(raw_length)

