#!/usr/bin/python3
##/usr/bin/env python3

from tkinter import Tk
from tkinter.messagebox import showinfo
import sys
import struct 
import pickle 

raw_length = sys.stdin.buffer.read(4)
if raw_length:
    root = Tk()
    root.withdraw()
    showinfo(title="Bad MF", message="TB is the GOAT")
    root.destroy()



